containers:
  apache-backend-eg:
    scheduler: random
    availability: per-pool
    instances:
      min: 3
      max: 3
      default: 3
    config:
      image: "stackhub/apache-backend-eg:latest"
      ports:
        - protocol: tcp
          container_port: "80"
    host_config:
      restart_policy: {}
